name: Build App

on:
    push:
        branches:
          - main
    pull_request:
        branches:
          - main
jobs:
    build:
        runs-on: ubuntu-latest

        steps:
        - name: Checkout repository
          uses: actions/checkout@v4

        - name: Set up JDK 21
          uses: actions/setup-java@v4
          with:
            distribution: 'temurin'
            java-version: '21'
            cache: 'gradle'

        - name: Build with Gradle (including test)
          run: ./gradlew build

        - name: Upload Artifact
          uses: actions/upload-artifact@v4
          with:
            name: HelloWorld.jar
            path: build/libs/HelloWorld-*.jar